version: '2.3'

services:
  prometheus:
    image: prometheus_prometheus
    build:
      context: ./prometheus
      args:
        TAG: 2.7.1-aarch64
        IMAGE: rycus86/prometheus

  cadvisor:
    build:
      context: ./cadvisor
      args:
        VERSION: v0.33.0
